---
- name: Install all apt dependencies
  become: yes
  user: ubuntu
  hosts: webserver
  gather_facts: yes
  roles:
    - server

- name: Setup mysql
  become: yes
  user: ubuntu
  hosts: webserver
  roles:
    - db

- name: Setup backup and disk space cron jobs
  become: yes
  user: ubuntu
  hosts: webserver
  roles:
    - backup

- name: Restore from backup
  become: yes
  user: ubuntu
  hosts: webserver
  roles:
    - role: restore
      when: DATE is defined

- name: Restart
  become: yes
  user: ubuntu
  hosts: webserver
  roles:
    - restart
